require: standard

inherit_gem:
  standard: config/base.yml

AllCops:
  TargetRubyVersion: 3.2
Style/StringLiterals:
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
